### ISSUE TITLE
Selecting a subscription does not always show their latest videos

### ISSUE THREAD

**Issue by fritzwf** [Protuhj/myvideobuzz#114] opened 2016-02-29 22:03 UTC
Sometimes when I am in the "Subscriptions" area and I select a particular subscription, the list of videos does not contain the latest video from that subscription.  I know there is a new video because I've seen in on their youtube page.  If I then go to the search feature and search for that subscriptions channel, say ChannelX, and select a video by that channel, then click "Show more videos from 'ChannelX", it will then display their latest video as the first video in the list.

**Comment by Protuhj** [comment] 2016-03-02 12:12
I think I know exactly what you're talking about -- and is part of the reason I switched most of the code over to the 'search' API endpoint versus the endpoint designed specifically for getting user videos.   

I'll keep an eye out and see if I can reproduce it and come up with a fix.

Have I mentioned I hate the new API?

**Comment by Protuhj** [comment] 2020-09-15 02:43
Closing due to project archival.

**Closed by Protuhj** 2020-09-15 02:43 UTC
